# Generated by Django 6.0.3 on 2026-03-19 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('acquisition_date', models.DateField()),
                ('acquisition_source', models.CharField(blank=True, help_text='Where you found it (address, dumpster, etc.)', max_length=200)),
                ('condition', models.CharField(choices=[('unknown', 'Unknown'), ('working', 'Working'), ('working_issues', 'Working with Issues'), ('not_working', 'Not Working'), ('parts_only', 'Parts Only')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('testing', 'Testing'), ('repairing', 'Repairing'), ('parting_out', 'Parting Out'), ('listed', 'Listed for Sale'), ('sold', 'Sold'), ('donated', 'Donated'), ('disposed', 'Disposed')], default='acquired', max_length=20)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, help_text='Your cost (usually $0 for trash finds)', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
            ],
            options={
                'ordering': ['-acquisition_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used in Repair'), ('sold', 'Sold'), ('discarded', 'Discarded')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item', models.ForeignKey(blank=True, help_text='Item this part was pulled from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_parts', to='inventory.item')),
                ('used_in_item', models.ForeignKey(blank=True, help_text='Item this part was used to repair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_parts', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('supplier', models.CharField(choices=[('ebay', 'eBay'), ('amazon', 'Amazon'), ('aliexpress', 'AliExpress'), ('other', 'Other')], default='other', max_length=50)),
                ('supplier_other', models.CharField(blank=True, help_text='Supplier name if "Other"', max_length=100)),
                ('order_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('received', 'Received'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_item', models.ForeignKey(blank=True, help_text='Item this order is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.item')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='What was sold (if not linked to an item/part above)', max_length=200)),
                ('sale_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform', models.CharField(choices=[('ebay', 'eBay'), ('facebook', 'Facebook Marketplace'), ('craigslist', 'Craigslist'), ('offerup', 'OfferUp'), ('local', 'Local / Cash'), ('other', 'Other')], default='other', max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='Platform fees, shipping costs, etc.', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.item')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.part')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_notes', to='inventory.category')),
            ],
            options={
                'ordering': ['make', 'model'],
                'unique_together': {('make', 'model')},
            },
        ),
    ]
