# Generated by Django 6.0.3 on 2026-03-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='eBay listing title', max_length=200)),
                ('ebay_item_id', models.CharField(blank=True, help_text='eBay item number', max_length=50)),
                ('starting_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_it_now', models.DecimalField(blank=True, decimal_places=2, help_text='Buy It Now price, if set', max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Winning bid / final sale price', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended_sold', 'Ended — Sold'), ('ended_unsold', 'Ended — Unsold'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='inventory.item')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='inventory.part')),
                ('sale', models.OneToOneField(blank=True, help_text='Sale record created when this auction converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='inventory.sale')),
            ],
            options={
                'ordering': ['-end_date', '-created_at'],
            },
        ),
    ]
